In [128]:
import pandas as pd

In [129]:
ripartizioni = pd.read_csv('output/shp_to_csv/ripartizioni.csv')
ripartizioni['cod_geografico'] = 'IT-' + ripartizioni['COD_RIP'].astype(str)
ripartizioni.rename(columns={'DEN_RIP': 'den_geografica'}, inplace=True)
ripartizioni['tipo_geografico'] = 'Ripartizione'
ripartizioni['parent_id'] = None
num_ripartizioni = len(ripartizioni)
ripartizioni.head()

,COD_RIP,den_geografica,Shape_Leng,Shape_Area,geometry,cod_geografico,tipo_geografico,parent_id
0,1,Nord-ovest,2.330675e+06,5.793083e+10,MULTIPOLYGON (((568227.8438999997 4874810.8690...,IT-1,Ripartizione,None
1,2,Nord-est,2.313109e+06,6.239611e+10,MULTIPOLYGON (((618343.9288999997 4893985.6603...,IT-2,Ripartizione,None
2,3,Centro,2.013166e+06,5.803001e+10,MULTIPOLYGON (((876021.9062999999 4524682.2958...,IT-3,Ripartizione,None
3,4,Sud,2.535023e+06,7.378181e+10,MULTIPOLYGON (((1083358.8458000002 4416348.740...,IT-4,Ripartizione,None
4,5,Isole,2.793918e+06,4.993062e+10,MULTIPOLYGON (((822901.3651999999 3935306.7218...,IT-5,Ripartizione,None

In [137]:
ISO_regioni = pd.read_csv('../input/ISO_Regioni.csv')
ISO_regioni.head()

  cod_geografico              DEN_REG
0          IT-21             Piemonte
1          IT-23        Valle d'Aosta
2          IT-25            Lombardia
3          IT-32  Trentino-Alto Adige
4          IT-34               Veneto

In [131]:
regioni = pd.read_csv('output/shp_to_csv/regioni.csv')
regioni = regioni.merge(ISO_regioni, left_on='DEN_REG', right_on='DEN_REG', how='inner')
regioni.rename(columns={'COD_RIP': 'parent_id', 'DEN_REG': 'den_geografica'}, inplace=True)
regioni['tipo_geografico'] = 'Regione'
num_regioni = len(regioni)
regioni.head()

,parent_id,COD_REG,den_geografica,Shape_Leng,Shape_Area,geometry,cod_geografico,tipo_geografico
0,1,1,Piemonte,1.234644e+06,2.539164e+10,"POLYGON ((457749.46360000037 5145501.7947, 458...",IT-21,Regione
1,1,2,Valle d'Aosta,3.111871e+05,3.258608e+09,"POLYGON ((390652.6434000004 5091766.170499999,...",IT-23,Regione
2,1,3,Lombardia,1.411360e+06,2.386287e+10,MULTIPOLYGON (((485536.4983999999 4985444.6364...,IT-25,Regione
3,2,4,Trentino-Alto Adige,8.007317e+05,1.360596e+10,"POLYGON ((743273.9085999997 5219762.9388, 7433...",IT-32,Regione
4,2,5,Veneto,1.056504e+06,1.835149e+10,"POLYGON ((768135.2094 5175357.4966, 768136.787...",IT-34,Regione

In [132]:
province = pd.read_csv('output/shp_to_csv/province.csv')
province['cod_geografico'] = 'IT-' + province['SIGLA']
province.rename(columns={'COD_REG': 'parent_id', 'DEN_UTS': 'den_geografica'}, inplace=True)
province.loc[province['den_geografica'] == 'Napoli', 'cod_geografico'] = province.loc[province['den_geografica'] == 'Napoli', 'cod_geografico'].fillna('IT-NA')
province['tipo_geografico'] = 'Provincia'
province['parent_id'] = province['parent_id'] + num_ripartizioni
province.head()

,COD_RIP,parent_id,COD_PROV,COD_CM,COD_UTS,DEN_PROV,DEN_CM,den_geografica,SIGLA,TIPO_UTS,Shape_Leng,Shape_Area,geometry,cod_geografico,tipo_geografico
0,1,6,1,201,201,-,Torino,Torino,TO,Città metropolitana,539673.515132,6.828372e+09,"POLYGON ((411015.2944 5049971.204500001, 41126...",IT-TO,Provincia
1,1,6,2,0,2,Vercelli,-,Vercelli,VC,Provincia,417425.499113,2.082173e+09,"POLYGON ((438328.7056 5087208.167099999, 43902...",IT-VC,Provincia
2,1,6,3,0,3,Novara,-,Novara,NO,Provincia,250657.226173,1.340540e+09,"POLYGON ((460929.5409000004 5076320.297, 46116...",IT-NO,Provincia
3,1,6,4,0,4,Cuneo,-,Cuneo,CN,Provincia,489291.467512,6.898186e+09,MULTIPOLYGON (((378672.6972000003 4958844.7530...,IT-CN,Provincia
4,1,6,5,0,5,Asti,-,Asti,AT,Provincia,312533.292987,1.508920e+09,"POLYGON ((425041.4112 4997628.2327, 424949.054...",IT-AT,Provincia

In [133]:
comuni = pd.read_csv('output/shp_to_csv/comuni.csv', na_values='', keep_default_na=False)
comuni.rename(columns={'COD_PROV': 'parent_id', 'COMUNE': 'den_geografica', 'PRO_COM':'cod_geografico'}, inplace=True)
comuni['tipo_geografico'] = 'Comune'
comuni['parent_id'] = comuni['parent_id'] + num_regioni
comuni.head()

,COD_RIP,COD_REG,parent_id,COD_CM,COD_UTS,cod_geografico,PRO_COM_T,den_geografica,COMUNE_A,CC_UTS,Shape_Leng,Shape_Area,geometry,tipo_geografico
0,1,1,21,0,201,1001,1001,Agliè,0,0,16075.204018,1.328507e+07,"POLYGON ((404703.5610999996 5026682.6555, 4053...",Comune
1,1,1,21,0,201,1002,1002,Airasca,0,0,16695.878036,1.578186e+07,"POLYGON ((380700.9090999998 4977305.5196, 3811...",Comune
2,1,1,21,0,201,1003,1003,Ala di Stura,0,0,29346.878200,4.576478e+07,"POLYGON ((364710.8563000001 5022090.677100001,...",Comune
3,1,1,21,0,201,1004,1004,Albiano d'Ivrea,0,0,16065.852912,1.137642e+07,"POLYGON ((415942.5100999996 5033304.612199999,...",Comune
4,1,1,21,0,201,1006,1006,Almese,0,0,16129.778623,1.779612e+07,"POLYGON ((376934.55030000024 4999073.8552, 376...",Comune

In [134]:
comuni.loc[comuni['den_geografica'] == 'None']

,COD_RIP,COD_REG,parent_id,COD_CM,COD_UTS,cod_geografico,PRO_COM_T,den_geografica,COMUNE_A,CC_UTS,Shape_Leng,Shape_Area,geometry,tipo_geografico
164,1,1,21,0,201,1168,1168,None,0,0,26888.783427,2.428520e+07,"POLYGON ((386380.0225999998 4981791.4606, 3863...",Comune

In [135]:
merge = pd.concat([ripartizioni, regioni, province, comuni], ignore_index=True)
merge['id'] = range(1, len(merge) + 1)
merge = merge[['id','parent_id','tipo_geografico','cod_geografico','den_geografica']]
print(merge)

        id parent_id tipo_geografico cod_geografico den_geografica
0        1      None    Ripartizione           IT-1     Nord-ovest
1        2      None    Ripartizione           IT-2       Nord-est
2        3      None    Ripartizione           IT-3         Centro
3        4      None    Ripartizione           IT-4            Sud
4        5      None    Ripartizione           IT-5          Isole
...    ...       ...             ...            ...            ...
8026  8027       131          Comune         111093         Ussana
8027  8028       131          Comune         111094    Ussaramanna
8028  8029       131          Comune         111095     Vallermosa
8029  8030       131          Comune         111096     Villacidro
8030  8031       131          Comune         111097       Villamar

[8031 rows x 5 columns]

In [136]:
merge.to_csv('output/dim_geografia.csv', index=False)